apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: neuralops
spec:
  selector:
    app: ingestion-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alerting-service
  namespace: neuralops
spec:
  selector:
    app: alerting-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-service
  namespace: neuralops
spec:
  selector:
    app: remediation-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
