apiVersion: v1
kind: Service
metadata:
  name: alerting-service
  labels:
    app: alerting-service
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: graphql
  selector:
    app: alerting-service
